version: '3.4'
services:
  redis:
    image: "redis:5.0.4-alpine"

  scheme-adapter:
    build:
      context: .
    env_file: ./src/test/config/integration.env
    ports:
      - "14000:4000"
      - "14001:4001"
      - "14002:4002"
    depends_on:
      - redis
